language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

notifications:
  email: false
  slack:
    secure: QMNMlTlEreXtJgmpjKTwSf6jNli3+aCCoxNjBjISVjA0yQYFY7K0JPvhnOanYY48OsqSSX8SYxbauMF48mBGxmveYKU9ZY2uoF+RIiCXNCcnomMQgIjyQATjWXB62SDEtik6vhBbEwsCOh7iKYz8o17Gsg1+V0K/pPVLL/NTks8=

before_install:
  - composer selfupdate

install:
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - test -e build/logs/clover.xml && wget https://scrutinizer-ci.com/ocular.phar
  - test -e build/logs/clover.xml && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
